config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'article/index'
  resources :stundents
  resources :users
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stundent.rb
class Stundent < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord

	# after_create_commit { broadcast_prepend_to 'todos' }
	# after_update_commit { broadcast_replace_to 'todos' }
	# after_destroy_commit { broadcast_remove_to 'todos' }
end

app/models/user.rb
class User < ApplicationRecord
  after_create_commit { broadcast_prepend_to "users"}
  after_update_commit { broadcast_replace_to "users"}
  after_destroy_commit { broadcast_remove_to "users"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stundents_controller.rb
class StundentsController < ApplicationController
  before_action :set_stundent, only: %i[ show edit update destroy ]

  # GET /stundents or /stundents.json
  def index
    @stundents = Stundent.all
  end

  # GET /stundents/1 or /stundents/1.json
  def show
  end

  # GET /stundents/new
  def new
    @stundent = Stundent.new
  end

  # GET /stundents/1/edit
  def edit
  end

  # POST /stundents or /stundents.json
  def create
    @stundent = Stundent.new(stundent_params)

    respond_to do |format|
      if @stundent.save
        format.html { redirect_to stundent_url(@stundent), notice: "Stundent was successfully created." }
        format.json { render :show, status: :created, location: @stundent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stundent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stundents/1 or /stundents/1.json
  def update
    respond_to do |format|
      if @stundent.update(stundent_params)
        format.turbo_stream
        format.html { redirect_to stundent_url(@stundent), notice: "Stundent was successfully updated." }
        format.json { render :show, status: :ok, location: @stundent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stundent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stundents/1 or /stundents/1.json
  def destroy
    @stundent.destroy

    respond_to do |format|
      format.html { redirect_to stundents_url, notice: "Stundent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stundent
      @stundent = Stundent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stundent_params
      params.require(:stundent).permit(:name)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        # format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.turbo_stream
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.turbo_stream
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.turbo_stream {render turbo_stream.remove "#{helpers.dom_id(@user)}_container"}
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurbooTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/stundents/_form.html.erb
<%= form_with(model: stundent, id: "#{dom_id(stundent)}_form",class: "contents") do |form| %>
  <% if stundent.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stundent.errors.count, "error") %> prohibited this stundent from being saved:</h2>

      <ul>
        <% stundent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/stundents/_stundent.html.erb
<div id="<%= "#{dom_id(stundent)}_container" %>">
  <%= turbo_frame_tag dom_id(stundent) do%>
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= stundent.name %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this stundent", stundent, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this stundent', edit_stundent_path(stundent), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  <%end%>
</div>

app/views/stundents/create.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(Stundent.new)}_form" do %>
  <%= render 'form', stundent: Stundent.new %>
<% end %>

app/views/stundents/edit.html.erb
<%= turbo_frame_tag "#{dom_id(@stundent)}"  do%>
   <%= render "form", stundent: @stundent %>
<% end %>

app/views/stundents/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Stundents</h1>
    <%= link_to 'New stundent', new_stundent_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="stundents" class="min-w-full">
    <%= render @stundents %>
  </div>
</div>

app/views/stundents/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New stundent</h1>

  <%= render "form", stundent: @stundent %>

  <%= link_to 'Back to stundents', stundents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stundents/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @stundent %>

    <%= link_to 'Edit this stundent', edit_stundent_path(@stundent), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this stundent', stundent_path(@stundent), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to stundents', stundents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/stundents/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@stundent)}_container" do %>
  <%= render 'stundent', stundent: @stundent %>
<%end%>

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex items-stretch flex-grow">
    <%= form.label :name, class: "sr-only" %>
    <%= form.text_field :name, class: "block w-full rounded-none rounded-l-md sm:text-sm border-gray-300", placeholder: "Add a new todo..." %>
    <%= form.submit class: "-ml-px relative px-4 py-2 border border-blue-600 text-sm font-medium rounded-r-md text-white bg-blue-600 hover:bg-blue-700" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<li id="<%= "#{dom_id(todo)}_container" %>" class="py-2 px-4 border-b border-gray-300">
  <%= turbo_frame_tag dom_id(todo) do%>
    <div class="flex justify-between items-center space-x-2">
      <%= link_to todo.name, edit_todo_path(todo) %>
      <%= button_to todo_path(todo), class: "bg-red-600 px-4 py-2 rounded hover:bg-red-700", method: :delete do %>
        <span class="sr-only">Delete</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor" title="Delete todo">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      <% end %>
    </div>
  <% end %>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.append "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
  <%= render "form", todo: Todo.new %>
<% end %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render 'form', todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<div class="mx-auto w-1/2">
  <h2 class="text-2xl text-gray-900">
    Your todos
  </h2>
  <div class="w-full max-w-2xl bg-gray-100 py-8 px-4 border border-gray-200 rounded shadow-sm">
    <div class="py-2 px-4">
      <%= render "form", todo: Todo.new %>
    </div>
    <%=turbo_stream_from "todos"%>
    <ul id="todos">
      <%= render @todos %>
    </ul>
  </div>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo %>

    <%= link_to 'Edit this todo', edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this todo', todo_path(@todo), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@todo)}_container" do %>
  <%= render "todo", todo: @todo %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, id: "#{dom_id(user)}_form", class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="flex items-stretch flex-grow">
      <%= form.label :name, class: "sr-only" %>
      <%= form.text_field :name, class: "block w-full rounded-none rounded-l-md sm:text-sm border-gray-300", placeholder: "Add a new todo..." %>
      <%= form.submit class: "-ml-px relative px-4 py-2 border border-blue-600 text-sm font-medium rounded-r-md text-white bg-blue-600 hover:bg-blue-700" %>
    </div>
<% end %>

app/views/users/_user.html.erb
<li id = "<%= "#{dom_id(user)}_container" %>", class="py-2 px-4 border-b border-gray-300">
    <%= turbo_frame_tag dom_id(user) do%>
    <div class="flex justify-between items-center space-x-2">
      <%= link_to user.name, edit_user_path(user) %>
      <%= button_to user_path(user), class: "bg-red-600 px-4 py-2 rounded hover:bg-red-700", method: :delete do %>
        <span class="sr-only">Delete</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor" title="Delete user">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      <% end %>
    </div>
  <% end %>
</li>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.append "users" do %>
  <%= render 'user', user: @user %>
<%end%>

<%= turbo_stream.replace "#{dom_id(User.new)}_form" do %>
  <%= render 'form', user: User.new %>
<% end %>

app/views/users/edit.html.erb
<%= turbo_frame_tag dom_id(@user) do %>
  <%= render "form", user: @user %>
<% end %>

app/views/users/index.html.erb
<div class="mx-auto w-1/2">
  <h2 class="text-2xl text-gray-900">
    Your users
  </h2>
  <div class="w-full max-w-2xl bg-gray-100 py-8 px-4 border border-gray-200 rounded shadow-sm">
    <div class="py-2 px-4">
      <%= render "form", user: User.new %>
    </div>
    <ul id="users">
      <%= render @users %>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@user)}_container" do %>
  <%= render "user", user: @user%>
<%end%>